config/routes.rb
Rails.application.routes.draw do

  get 'panel_instructor_diplomados', to: 'panel_instructor_diplomados#index'
  get 'calificacion_diplomados', to: 'panel_instructor_diplomados#calificacion_diplomados'

  resources :inscripcion_diplomados
  resources :calificacion_modulos do
    collection do
      patch 'actualizar_calificaciones'
    end
  end
  resources :grupos_diplomados do
    collection do
      get 'acta/:id', to: 'grupos_diplomados#acta', as: 'acta'
      get 'lista_dec/:id', to: 'grupos_diplomados#lista_dec', as: 'lista_dec'
      get 'lista_cec/:id', to: 'grupos_diplomados#lista_cec', as: 'lista_cec'
      get 'expedicion_diplomas/:id', to: 'grupos_diplomados#expedicion_diplomas', as: 'expedicion_diplomas'
    end
  end
  resources :diplomados
  resources :buscar_cartas do
    collection do
      get :carta
    end
  end

  resources :grupos_unitarios do
    collection do
      get 'grupo_excel/:id', to: 'grupos_unitarios#grupo_excel', as: 'grupo_excel'
      get 'grupo_correo/:id', to: 'grupos_unitarios#grupo_correo', as: 'grupo_correo'
    end
  end
  resources :unitarios do
    collection do
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'asignar_grupos_nms_s'
      get 'grupos_nms_s'
      patch 'actualizar_grupos_nms_s'
      get '/credenciales_media/:id', to: 'unitarios#credenciales_media', as: 'credenciales_media'
      get '/carta_compromiso/:id', to: 'unitarios#carta_compromiso', as: 'carta_compromiso'
      get 'reporte_dems'
      get 'reporte_no_validados'
      get 'reporte_contactos'
      get 'generar_credenciales'
      get 'imprimir_credenciales_media'
      get 'imprimir_credenciales_superior'
      get 'imprimir_credenciales_media_grupo'
      get 'imprimir_credenciales_superior_grupo'
    end
  end
  resources :anexos_unicos_examen do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :seccion_nombres
  resources :anexos_unicos do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :it_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'it_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :fr_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'fr_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :curriculums
  resources :registro_cursos
  resources :examen_colocacion_idiomas
  resources :constancia
  resources :historial_carta
  resources :grupo_datos
  resources :datos_bancos
  resources :numero_registros
  resources :proyectos
  resources :clave_catalogos
  resources :cuota_cursos
  resources :modalidad_oferta
  resources :tipo_oferta
  resources :centros
  resources :materia
  resources :lugar_nombres
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :roles
  resources :users do
    collection do
      get 'instructores'
      get 'historiales_ingles'
      get 'historial_ingles/:id', to: 'users#historial_ingles', as: 'historial_ingles'
      get 'anexos_unicos/:id', to: 'users#anexos_unicos', as: 'anexos_unicos'
      get 'conclusion_eventos', to: 'users#conclusion_eventos', as: 'conclusion_eventos'
      get 'datos_anexo_unico'
      get 'generar_anexo_unico'
      get 'historial_academico_ingles/:id', to: 'users#historial_academico_ingles', as: 'historial_academico_ingles'
      get 'historiales_frances'
      get 'historial_frances/:id', to: 'users#historial_frances', as: 'historial_frances'
      get 'historial_academico_frances/:id', to: 'users#historial_academico_frances', as: 'historial_academico_frances'
      get 'historiales_italiano'
      get 'historial_italiano/:id', to: 'users#historial_italiano', as: 'historial_italiano'
      get 'historial_academico_italiano/:id', to: 'users#historial_academico_italiano', as: 'historial_academico_italiano'
      get 'historiales_b2'
      get 'historial_b2/:id', to: 'users#historial_b2', as: 'historial_b2'
      get 'historial_academico_b2/:id', to: 'users#historial_academico_b2', as: 'historial_academico_b2'
      get 'historiales_tkt'
      get 'historial_tkt/:id', to: 'users#historial_tkt', as: 'historial_tkt'
      get 'historial_academico_tkt/:id', to: 'users#historial_academico_tkt', as: 'historial_academico_tkt'
      get 'historiales'
    end
  end
  resources :estados
  resources :grupos do
    collection do
      post 'edit_multiple'
      patch 'update_multiple'
      get 'crear_constancias/:id', to: 'grupos#crear_constancias',  as: 'crear_constancias'
      get 'calificaciones/:id', to: 'grupos#calificaciones', as: 'calificaciones'
      get 'apertura/:id', to: 'grupos#apertura', as: 'apertura'
      get 'lista_asistencia/:id', to: 'grupos#lista_asistencia', as: 'lista_asistencia'
      get 'supervisar/:id', to: 'grupos#supervisar', as: 'supervisar'
    end
  end
  #resources :profesor_nombres
  resources :generos
  resources :curso_nombres
  resources :calendarios
  resources :procedencia
  resources :cuota
  resources :nivel_nombres
  resources :idiomas
  resources :horarios
  resources :inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec_frances'
      get 'reporte_dec_italiano'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'caso_especial'
      post 'guardar_caso_especial'
      get 'certificacion'
      get '/talon/:id', to: 'inscripcion_registros#talon', as: 'talon'
      get '/constancia_avanzado/:id', to: 'inscripcion_registros#constancia_avanzado', as: 'constancia_avanzado'
      get 'ver_constancias_tkt'
      get '/constancia_tkt/:id', to: 'inscripcion_registros#constancia_tkt', as: 'constancia_tkt'
      get 'ver_constancias_b2'
      get '/constancia_b2/:id', to: 'inscripcion_registros#constancia_b2', as: 'constancia_b2'
    end
  end
  resources :panel_alumnos do
    collection do
      get 'facturacion'
      get 'regulaciones'
    end
  end
  resources :panel_profesores do
    collection do
      get 'mis_grupos'
      get 'historial_academico'
    end
  end
  get '/panel_control_escolar/', to: 'panel_control_escolar#index'

  resources :reinscripcion_registros do
    collection do
      get :boleta
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_scope :user do
    #root to: "devise/sessions#new"
  #end
  root to: "inicio#index"
end

app/models/grupos_unitario.rb
class GruposUnitario < ApplicationRecord

  has_many :unitarios

  paginates_per 25

  def jefe_educacion_continua
    rol = Role.find_by(nombre: "Jefe Educación Continua").id
    usuarios = User.find_by(role: rol).nombre_paterno_materno
  end

  def self.seleccion_curso_nombre
    order('LOWER(nombre)').map { |e| [e.nombre, e.id] }
  end

  def self.seleccion_grupo_nombre
    order('LOWER(nombre)').map { |e| [e.nombre_grupo, e.id] }
  end

  def nombre_grupo
    "#{nombre} #{seccion}"
  end

end

app/controllers/grupos_unitarios_controller.rb
class GruposUnitariosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_grupos_unitario, only: [:show, :edit, :update, :destroy]
  before_action :grupos_unitario, only: :create
  load_and_authorize_resource

  # GET /grupos_unitarios
  # GET /grupos_unitarios.json
  def index
    @grupos_unitarios = GruposUnitario.order('nombre ASC')
  end

  # GET /grupos_unitarios/1
  # GET /grupos_unitarios/1.json
  def show
    @unitarios = Unitario.where(documentos_validados: true, grupos_unitario_id: @grupos_unitario.id).order('paterno ASC, materno ASC, nombre ASC')
    @inscritos = Unitario.where(documentos_validados: true, grupos_unitario_id: @grupos_unitario.id).count
  end

  # GET /grupos_unitarios/new
  def new
    @grupos_unitario = GruposUnitario.new
  end

  # GET /grupos_unitarios/1/edit
  def edit
  end

  # POST /grupos_unitarios
  # POST /grupos_unitarios.json
  def create
    @grupos_unitario = GruposUnitario.new(grupos_unitario_params)

    respond_to do |format|
      if @grupos_unitario.save
        format.html { redirect_to @grupos_unitario, notice: 'El grupo se creó correctamente.' }
        format.json { render :show, status: :created, location: @grupos_unitario }
      else
        format.html { render :new }
        format.json { render json: @grupos_unitario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos_unitarios/1
  # PATCH/PUT /grupos_unitarios/1.json
  def update
    #respond_to do |format|
      if @grupos_unitario.update(grupos_unitario_params)
        if user_signed_in? && current_user.role.nombre == "Administrador"
          redirect_to unitarios_path, notice: 'El grupo se actualizó correctamente'
          elsif user_signed_in? && current_user.role.nombre == "Cursos control"
            redirect_to unitarios_path, notice: 'El grupo se actualizó correctamente'
          else
          format.html { redirect_to @grupos_unitario, notice: 'El grupo se actualizó correctamente.' }
          format.json { render :show, status: :ok, location: @grupos_unitario }
        end
      else
        format.html { render :edit }
        format.json { render json: @grupos_unitario.errors, status: :unprocessable_entity }
      end
    #end
  end

  # DELETE /grupos_unitarios/1
  # DELETE /grupos_unitarios/1.json
  def destroy
    if @grupos_unitario.unitarios.any?
      redirect_to grupos_unitarios_path, alert: 'El grupo que intenta eliminar no está vacío. Primero mueva los registros a otro grupo o elimínelos.'
    else
      @grupos_unitario.destroy
      respond_to do |format|
        format.html { redirect_to grupos_unitarios_url, notice: 'El grupo se eliminó correctamente.' }
        format.json { head :no_content }
      end
    end
  end

  def grupo_excel
    # Se utiliza la variable @unitarios para generar el documento en hoja de
    # cálculo con todos los registros unitarios validados, tambien se puede
    # utilizar en la vista
    @unitarios = Unitario.where(documentos_validados: true, grupos_unitario_id: @grupos_unitario.id).order('paterno ASC, materno ASC, nombre ASC')
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def grupo_correo
    # Se utiliza la variable @unitarios para generar el documento en hoja de
    # cálculo con todos los registros unitarios validados, tambien se puede
    # utilizar en la vista
    @unitarios = Unitario.where(documentos_validados: true, grupos_unitario_id: @grupos_unitario.id).order('paterno ASC, materno ASC, nombre ASC')
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupos_unitario
      @grupos_unitario = GruposUnitario.find(params[:id])
    end

    def grupos_unitario
      @grupos_unitario = GruposUnitario.new(grupos_unitario_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupos_unitario_params
      params.require(:grupos_unitario).permit(:nombre, :horario, :estado, :anio,
      :periodo, :lugar, :fecha, :centro, :tipo, :modalidad, :cupo, :duracion, :cuota, :clave,
      :proyecto, :institucion_bancaria, :cuenta, :titular, :jefe_ec, :registro, :referencia,
      :habilitar_constancias_grupo, :seccion)
    end
end

app/helpers/grupos_unitarios_helper.rb
module GruposUnitariosHelper
end

app/views/grupos_unitarios/_form.html.erb
<%= form_for(grupos_unitario) do |f| %>
  <% if grupos_unitario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grupos_unitario.errors.count, "error") %> prohibited this grupos_unitario from being saved:</h2>

      <ul>
      <% grupos_unitario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row  jumbotron">
  <h4 class="subs"><strong>Informaci&oacute;n general del grupo</strong></h4>
  <div class="form-group col-sm-3">
    <%= f.label :nombre, 'Nombre del curso' %>
    <%= collection_select(:grupos_unitario, :nombre, RegistroCurso.all, :nombre, :nombre, {prompt: 'Seleccione'}, class: 'form-control') %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :horario %>
    <%= f.text_field :horario, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :estado %>
    <%= collection_select(:grupos_unitario, :estado, Estado.all, :nombre, :nombre, {prompt: 'Seleccione'}, class: 'form-control') %>
  </div>

  <div class="form-group col-sm-2">
    <%= f.label :anio, 'Año' %><br>
    <div class="input-group date">
      <%= f.text_field :anio, class:'anio form-control' %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :periodo %>
    <%= f.text_field :periodo, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :seccion %>
    <%= collection_select(:grupos_unitario, :seccion, SeccionNombre.order('nombre ASC'), :nombre, :nombre, {prompt: 'Seleccione'}, class: 'form-control') %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :habilitar_constancias_grupo %>
    <%= f.check_box :habilitar_constancias_grupo, class:'form-control' %>
  </div>
</div>
<div class="row  jumbotron">
  <h4 class="subs"><strong>Informaci&oacute;n de la oferta educativa</strong></h4>
  <div class="form-group col-sm-3">
    <%= f.label :lugar %>
    <%= collection_select(:grupos_unitario, :lugar, Centro.all, :lugar, :lugar, {prompt: 'Seleccione'}, class: 'form-control') %>
  </div>

  <div class="form-group col-sm-2">
    <%= f.label :fecha, 'Fecha' %><br>
    <div class="input-group date">
      <%= f.text_field :fecha, class:'fecha form-control' %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :centro %>
    <%= collection_select(:grupos_unitario, :centro, Centro.all, :nombre, :nombre, {prompt: 'Seleccione'}, class: 'form-control') %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :registro %>
    <%= f.text_field :registro, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :tipo %>
    <%= f.text_field :tipo, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :modalidad %>
    <%= f.text_field :modalidad, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :cupo %>
    <%= f.text_field :cupo, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :duracion %>
    <%= f.text_field :duracion, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :cuota %>
    <%= f.text_field :cuota, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :clave, 'Clave del catálogo fideicomiso' %>
    <%= f.text_field :clave, class:'form-control' %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :proyecto %>
    <%= f.text_field :proyecto, class:'form-control' %>
  </div>
</div>
<div class="row  jumbotron">
  <h4 class="subs"><strong>Informaci&oacute;n bancaria</strong></h4>
  <div class="form-group col-sm-3">
    <%= f.label :institucion_bancaria %>
    <%= collection_select(:grupos_unitario, :institucion_bancaria, DatosBanco.all, :nombre, :nombre, {prompt: 'Seleccione'}, class: 'form-control')  %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :cuenta %>
    <%= collection_select(:grupos_unitario, :cuenta, DatosBanco.all, :cuenta, :cuenta, {prompt: 'Seleccione'}, class: 'form-control')  %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :titular %>
    <%= collection_select(:grupos_unitario, :titular, DatosBanco.all, :titular, :titular, {prompt: 'Seleccione'}, class: 'form-control')  %>
  </div>

  <div class="form-group col-sm-3">
    <%= f.label :referencia %>
    <%= collection_select(:grupos_unitario, :referencia, DatosBanco.all, :referencia, :referencia, {prompt: 'Seleccione'}, class: 'form-control')  %>
  </div>
</div>
<div class="row  jumbotron">
  <h4 class="subs"><strong>Validaci&oacute;n</strong></h4>
  <div class="form-group col-sm-3">
    <%= f.label :jefe_ec, 'Jefe de Educación Continua' %>
    <%= f.text_field :jefe_ec, value: grupos_unitario.jefe_educacion_continua, class: 'form-control'  %>
  </div>
</div>
<div class="row">
  <div class="actions col-sm-4">
    <%= f.submit 'Enviar', class:'btn btn-primary' %>
  </div>
</div>
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $('.anio').datepicker({language: 'es', format: 'yyyy', minViewMode: 'years'});
    $('.fecha').datepicker({language: 'es', format: 'dd-mm-yyyy', todayHighlight: true});
  });
</script>

app/views/grupos_unitarios/edit.html.erb
<h1 class="sub">Editar grupo</h1>

<%= render 'form', grupos_unitario: @grupos_unitario %>

<%= link_to 'Mostrar', @grupos_unitario %> |
<%= link_to 'Regresar', grupos_unitarios_path %>

app/views/grupos_unitarios/index.html.erb
<h1 class="sub">Grupos de cursos unitarios</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Seccion</th>
      <th>Horario</th>
      <th>Periodo</th>
      <th>Año</th>
      <th>Estado</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos_unitarios.each do |grupos_unitario| %>
      <tr>
        <td><%= grupos_unitario.nombre %></td>
        <td><%= grupos_unitario.seccion %></td>
        <td><%= grupos_unitario.horario %></td>
        <td><%= grupos_unitario.periodo %></td>
        <td><%= grupos_unitario.anio %></td>
        <td><%= grupos_unitario.estado %></td>
        <td><%= link_to 'Descargar', grupo_excel_grupos_unitarios_path(grupos_unitario, format: :xlsx) %></td>
        <td><%= link_to 'Mostrar', grupos_unitario %></td>
        <td><%= link_to 'Editar', edit_grupos_unitario_path(grupos_unitario) %></td>
        <td><%= link_to 'Eliminar', grupos_unitario, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear nuevo grupo', new_grupos_unitario_path %>

app/views/grupos_unitarios/new.html.erb
<h1 class="sub">Crear nuevo grupo</h1>

<%= render 'form', grupos_unitario: @grupos_unitario %>

<%= link_to 'Regresar', root_path %>

app/views/grupos_unitarios/show.html.erb
<div id="grupos">
<p><strong>Nombre del profesor:</strong> <%#= @grupo.user.nombre_completo %></p>
<p><strong>Grupo:</strong> <%= @grupos_unitario.nombre_grupo %></p>
<p><strong>Horario:</strong> <%= @grupos_unitario.horario %></p>
<p><strong>Inscritos:</strong> <%= @inscritos %></p>
  <%= form_tag(asignar_calificaciones_unitarios_path, method: :get) do %>
  <table class="table table-bordered table-hover">
    <thead>
      <% if can? :editar_datos, @grupos_unitario %>
        <!--<#% if @grupo.estado == "Abierto" %>-->
          <th></th>
        <!--<#% end %>-->
      <% end %>
        <th width="5%">N&uacute;mero de lista</th>
        <th>Apellido paterno</th>
        <th>Apellido materno</th>
        <th>Nombre</th>
        <th>Examen final</th>
      </tr>
    </thead>

    <tbody>
        <% @unitarios.each_with_index do |unitario, index| %>
            <tr>
              <% if can? :editar_datos, @grupos_unitario %>
                <td><%= check_box_tag "unitario_ids[]", unitario.id %></td>
              <% end %>
              <td><%= index + 1 %></td>
              <td><%= unitario.paterno %></td>
              <td><%= unitario.materno %></td>
              <td><%= unitario.nombre %></td>
              <td><%= unitario.examen_final %></td>
            </tr>
        <% end %>
    </tbody>
  </table>
    <% if can? :editar_datos, @grupos_unitario %>
        <input type="checkbox" id="selectAll" value="selectAll"><strong> Seleccionar / Deseleccionar todos</strong><br><br>
        <%= submit_tag "Asignar calificaciones", class:'btn btn-primary' %>
    <% end %>
  <% end %>
  <br>
  <%= link_to 'Regresar', grupos_unitarios_path %>
  <script>
  $('#selectAll').click(function() {
     if (this.checked) {
         $(':checkbox').each(function() {
             this.checked = true;
         });
     } else {
        $(':checkbox').each(function() {
             this.checked = false;
         });
     }
  });
  </script>