config/routes.rb
Rails.application.routes.draw do

  get 'panel_instructor_diplomados', to: 'panel_instructor_diplomados#index'
  get 'calificacion_diplomados', to: 'panel_instructor_diplomados#calificacion_diplomados'

  resources :inscripcion_diplomados
  resources :calificacion_modulos do
    collection do
      patch 'actualizar_calificaciones'
    end
  end
  resources :grupos_diplomados do
    collection do
      get 'acta/:id', to: 'grupos_diplomados#acta', as: 'acta'
      get 'lista_dec/:id', to: 'grupos_diplomados#lista_dec', as: 'lista_dec'
      get 'lista_cec/:id', to: 'grupos_diplomados#lista_cec', as: 'lista_cec'
      get 'expedicion_diplomas/:id', to: 'grupos_diplomados#expedicion_diplomas', as: 'expedicion_diplomas'
    end
  end
  resources :diplomados
  resources :buscar_cartas do
    collection do
      get :carta
    end
  end

  resources :grupos_unitarios do
    collection do
      get 'grupo_excel/:id', to: 'grupos_unitarios#grupo_excel', as: 'grupo_excel'
      get 'grupo_correo/:id', to: 'grupos_unitarios#grupo_correo', as: 'grupo_correo'
    end
  end
  resources :unitarios do
    collection do
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'asignar_grupos_nms_s'
      get 'grupos_nms_s'
      patch 'actualizar_grupos_nms_s'
      get '/credenciales_media/:id', to: 'unitarios#credenciales_media', as: 'credenciales_media'
      get '/carta_compromiso/:id', to: 'unitarios#carta_compromiso', as: 'carta_compromiso'
      get 'reporte_dems'
      get 'reporte_no_validados'
      get 'reporte_contactos'
      get 'generar_credenciales'
      get 'imprimir_credenciales_media'
      get 'imprimir_credenciales_superior'
      get 'imprimir_credenciales_media_grupo'
      get 'imprimir_credenciales_superior_grupo'
    end
  end
  resources :anexos_unicos_examen do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :seccion_nombres
  resources :anexos_unicos do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :it_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'it_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :fr_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'fr_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :curriculums
  resources :registro_cursos
  resources :examen_colocacion_idiomas
  resources :constancia
  resources :historial_carta
  resources :grupo_datos
  resources :datos_bancos
  resources :numero_registros
  resources :proyectos
  resources :clave_catalogos
  resources :cuota_cursos
  resources :modalidad_oferta
  resources :tipo_oferta
  resources :centros
  resources :materia
  resources :lugar_nombres
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :roles
  resources :users do
    collection do
      get 'instructores'
      get 'historiales_ingles'
      get 'historial_ingles/:id', to: 'users#historial_ingles', as: 'historial_ingles'
      get 'anexos_unicos/:id', to: 'users#anexos_unicos', as: 'anexos_unicos'
      get 'conclusion_eventos', to: 'users#conclusion_eventos', as: 'conclusion_eventos'
      get 'datos_anexo_unico'
      get 'generar_anexo_unico'
      get 'historial_academico_ingles/:id', to: 'users#historial_academico_ingles', as: 'historial_academico_ingles'
      get 'historiales_frances'
      get 'historial_frances/:id', to: 'users#historial_frances', as: 'historial_frances'
      get 'historial_academico_frances/:id', to: 'users#historial_academico_frances', as: 'historial_academico_frances'
      get 'historiales_italiano'
      get 'historial_italiano/:id', to: 'users#historial_italiano', as: 'historial_italiano'
      get 'historial_academico_italiano/:id', to: 'users#historial_academico_italiano', as: 'historial_academico_italiano'
      get 'historiales_b2'
      get 'historial_b2/:id', to: 'users#historial_b2', as: 'historial_b2'
      get 'historial_academico_b2/:id', to: 'users#historial_academico_b2', as: 'historial_academico_b2'
      get 'historiales_tkt'
      get 'historial_tkt/:id', to: 'users#historial_tkt', as: 'historial_tkt'
      get 'historial_academico_tkt/:id', to: 'users#historial_academico_tkt', as: 'historial_academico_tkt'
      get 'historiales'
    end
  end
  resources :estados
  resources :grupos do
    collection do
      post 'edit_multiple'
      patch 'update_multiple'
      get 'crear_constancias/:id', to: 'grupos#crear_constancias',  as: 'crear_constancias'
      get 'calificaciones/:id', to: 'grupos#calificaciones', as: 'calificaciones'
      get 'apertura/:id', to: 'grupos#apertura', as: 'apertura'
      get 'lista_asistencia/:id', to: 'grupos#lista_asistencia', as: 'lista_asistencia'
      get 'supervisar/:id', to: 'grupos#supervisar', as: 'supervisar'
    end
  end
  #resources :profesor_nombres
  resources :generos
  resources :curso_nombres
  resources :calendarios
  resources :procedencia
  resources :cuota
  resources :nivel_nombres
  resources :idiomas
  resources :horarios
  resources :inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec_frances'
      get 'reporte_dec_italiano'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'caso_especial'
      post 'guardar_caso_especial'
      get 'certificacion'
      get '/talon/:id', to: 'inscripcion_registros#talon', as: 'talon'
      get '/constancia_avanzado/:id', to: 'inscripcion_registros#constancia_avanzado', as: 'constancia_avanzado'
      get 'ver_constancias_tkt'
      get '/constancia_tkt/:id', to: 'inscripcion_registros#constancia_tkt', as: 'constancia_tkt'
      get 'ver_constancias_b2'
      get '/constancia_b2/:id', to: 'inscripcion_registros#constancia_b2', as: 'constancia_b2'
    end
  end
  resources :panel_alumnos do
    collection do
      get 'facturacion'
      get 'regulaciones'
    end
  end
  resources :panel_profesores do
    collection do
      get 'mis_grupos'
      get 'historial_academico'
    end
  end
  get '/panel_control_escolar/', to: 'panel_control_escolar#index'

  resources :reinscripcion_registros do
    collection do
      get :boleta
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_scope :user do
    #root to: "devise/sessions#new"
  #end
  root to: "inicio#index"
end

app/models/role.rb
class Role < ApplicationRecord

  has_many :users

  def self.options_for_select
    order('LOWER(nombre)').map { |e| [e.nombre, e.id] }
  end

end

app/controllers/anexos_unicos_examen_controller.rb
class AnexosUnicosExamenController < ApplicationController

  def index
      @users = User.instructores.order(:paterno).page params[:pagina]
  end

  def imprimir_anexo_unico
    @instructores = User.where(id: params[:user_ids])
    @curso = CursoNombre.find_by(nombre: params[:curso]).nombre
    @periodo = Grupo.find_by(anio: params[:anio], curso: params[:curso]).periodo
    @anio = Grupo.find_by(anio: params[:anio]).anio
    @mes = mes
  end

  def mes
    if Date.today.strftime("%b") == "Jan"
      mes = "Enero"
    elsif Date.today.strftime("%b") == "Feb"
      mes = "Febrero"
    elsif Date.today.strftime("%b") == "Mar"
      mes = "Marzo"
    elsif Date.today.strftime("%b") == "Apr"
      mes = "Abril"
    elsif Date.today.strftime("%b") == "May"
      mes = "Mayo"
    elsif Date.today.strftime("%b") == "Jun"
      mes = "Junio"
    elsif Date.today.strftime("%b") == "Jul"
      mes = "Julio"
    elsif Date.today.strftime("%b") == "Aug"
      mes = "Agosto"
    elsif Date.today.strftime("%b") == "Sep"
      mes = "Septiembre"
    elsif Date.today.strftime("%b") == "Oct"
      mes = "Octubre"
    elsif Date.today.strftime("%b") == "Nov"
      mes = "Noviembre"
    elsif Date.today.strftime("%b") == "Dec"
      mes = "Diciembre"
    end
  end

end

app/helpers/anexos_unicos_examen_helper.rb
module AnexosUnicosExamenHelper
end

app/views/anexos_unicos_examen/imprimir_anexo_unico.html.erb
<div id="anexos-unicos">
<% @instructores.each do |instructor| %>
<p style="page-break-before: always;">&nbsp;</p>
    <table border="0" width="659">
    <tr>
      <td width="200">
        <p align="left"><%= image_tag "cabecera_sep.png" %></p>
      </td>
      <td colspan="2" width="1400">
      </td>
      <td width="200">
        <p align="right"><%= image_tag "cabecera_cec.png" %></p>
      </td>
    </tr>
    </table>
    <p align="center"><strong><u>ANEXO  ÚNICO</u></strong></p>
    <p align="right"><strong>Ciudad de México, a <%= Date.today.strftime("%d") %> de  <%= @mes %> de <%= Date.today.strftime("%Y") %></strong></p>
    <p>El  objeto de este documento consiste en el desarrollo de programa académico:
      <br />
      Aplicación de Exámenes de Colocación de los CELEX. <%= @curso %>.
      <hr>
    </p>
    <p>Nombre  del prestador:
      <br /><%= instructor.nombre_completo %>
      <hr>
    </p>
    <p><strong>PROGRAMA  ACADÉMICO:</strong><strong> </strong><strong> </strong></p>
    <table class="table table-bordered" width="659">
      <tr>
        <td width="149" colspan="2"><p><strong>TIPO DE PROGRAMA</strong></p></td>
        <td width="161" colspan="3"><p><strong>ORDEN DE SERVICIO</strong></p></td>
        <td width="350" colspan="5"><p><strong>CEC INGENIERO EUGENIO MÉNDEZ DOCURRO</strong></p></td>
      </tr>
      <tr>
        <td width="81"><p><strong>Instructor:</strong></p></td>
        <td width="159" colspan="3"><p><strong>( ) Interno IPN</strong></p></td>
        <td width="123" colspan="3"><p><strong>( ) Docente</strong></p></td>
        <td width="151"><p><strong>( ) Administrativo</strong></p></td>
        <td width="145" colspan="2"><p><strong>(X) Externo</strong></p></td>
      </tr>
    </table>
    <table class="table table-bordered" width="659">
      <tr>
        <td width="217" colspan="3"><p><strong>Periodo:</strong>

          <%= @curso %> <%= @periodo %> de <%= @anio %><strong></strong></p></td>

        <td width="189" colspan="3"><p><strong>Costo total.</strong><br />
          <%=
          examenes_comunidad = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo, curso: params[:curso], anio: params[:anio], procedencia: "Instituto Politécnico Nacional").count
          examenes_publico = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo, curso: params[:curso], anio: params[:anio], procedencia: "Otro").count
          total_comunidad = examenes_comunidad * 54.25
          total_publico = examenes_publico * 180.50
          total = total_comunidad + total_publico
          "$#{total} + I.V.A."
          %>
        </p></td>
        <td width="130" colspan="3"><p><strong>Pago único neto.</strong><br />
          <%=
          examenes_comunidad = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo, curso: params[:curso], anio: params[:anio], procedencia: "Instituto Politécnico Nacional").count
          examenes_publico = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo, curso: params[:curso], anio: params[:anio], procedencia: "Otro").count
          total_comunidad = examenes_comunidad * 54.25
          total_publico = examenes_publico * 180.50
          total = total_comunidad + total_publico
          iva = total * 0.16
          total_final_iva = total + iva
          retencion_iva = total * 0.106666
          retencion_isr = total * 0.1
          retenciones = retencion_isr + retencion_iva
          total_final_iva = total_final_iva - retenciones
          "$#{total_final_iva.round(2)}"
          %>
        </p></td>
      </tr>
      <tr>
        <td width="659" colspan="10"><p><strong>Exámenes:</strong>
          <% examenes_comunidad = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo,
          curso: params[:curso], anio: params[:anio], procedencia: "Instituto Politécnico Nacional").count %>
          <% examenes_publico = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo,
          curso: params[:curso], anio: params[:anio], procedencia: "Otro").count %>
          <% if examenes_comunidad == 1 %>
            <%= "1 examen de la Comunidad Politécnica" %>
          <% elsif examenes_comunidad == 0 %>
          <% elsif examenes_comunidad > 1 %>
            <%= "#{examenes_comunidad} exámenes de la Comunidad Politécnica" %>
          <% end %>
          <% if examenes_publico == 1 %>
            <%= " y 1 examen de Público General" %>
          <% elsif examenes_publico == 0 %>
          <% elsif examenes_publico > 1 %>
            <%= " y #{examenes_publico} exámenes de Público General" %>
          <% end %>
          .
        </p></td>
      </tr>
      <tr>
        <td width="659" colspan="10"><p><strong>Sede:</strong><br />
          Centro de Educación Continua Unidad Ingeniero Eugenio Méndez Docurro. Belisario Domínguez 22, Col. Centro<strong></strong></p></td>
      </tr>
    </table>
    <p><strong>PROGRAMA  DE ACTIVIDADES:</strong></p>
    <ul>
      <li><u>Aplicación de exámenes de colocación de los CELEX.</u></li>
    </ul>
    <table width="690">
      <tr>
        <td width="196" valign="top"><p align="center"><strong>PRESTADOR</strong></p>

            <p align="center"><strong>&nbsp;</strong></p>

          <p align="center"><strong><%= instructor.nombre_upcase %></strong></p></td>
        <td width="284" valign="top"><p align="center"><strong>RESPONSABLE DE SUPERVISAR Y VIGILAR</strong></p>

            <p align="center"><strong>&nbsp;</strong></p>

          <p align="center"><strong><%= User.subdirector %> </strong></p></td>
        <td width="210" valign="top"><p align="center"><strong>DIRECTOR</strong></p>

            <p align="center"><strong>&nbsp;</strong></p>

          <p align="center"><strong>DR. RICARDO OCTAVIO ARTURO MOTA PALOMINO</strong></p></td>
      </tr>
    </table>
    <p style="page-break-after: always;">&nbsp;</p>
<% end %>
</div>
<div id="conclusiones-evento">
<% @instructores.each do |instructor| %>
<p style="page-break-before: always;">&nbsp;</p>
    <table border="0" width="659">
    <tr>
      <td width="200">
        <p align="left"><%= image_tag "cabecera_sep.png" %></p>
      </td>
      <td colspan="2" width="1400">
      </td>
      <td width="200">
        <p align="right"><%= image_tag "cabecera_cec.png" %></p>
      </td>
    </tr>
    </table>
    <p align="left"><strong><u>CONCLUSIÓN DE EVENTO ACADÉMICO</u></strong></p>
    <p align="right"><strong>Ciudad de México, a <%= Date.today.strftime("%d") %> de  <%= @mes %> de <%= Date.today.strftime("%Y") %></strong></p>
    <p>C.P. JOAQUÍN TREJO BARRÓN<br>
      JEFE DEL DEPARTAMENTO DE SERVICIOS<br>
        ADMINISTRATIVOS Y TÉCNICOS<br>
        P R E S E N T E :</p>
      <p>&nbsp;</p>
      <p>Por este medio le informamos que el (la) <strong><u>Prof. <%= instructor.nombre_completo %> </u></strong></p>
      <p>Cumplió satisfacortiamente</p>
      <p>&nbsp;</p>
      <ul>
        <li>La aplicación de Exámenes de colocación que a continuación enlisto:
        <br>
        <% examenes_comunidad = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo,
        curso: params[:curso], anio: params[:anio], procedencia: "Instituto Politécnico Nacional").count %>
        <% examenes_publico = ExamenColocacionIdioma.where(examinador: instructor.nombre_completo,
        curso: params[:curso], anio: params[:anio], procedencia: "Otro").count %>
        <% if examenes_comunidad == 1 %>
          <%= "1 examen de la Comunidad Politécnica" %>
        <% elsif examenes_comunidad == 0 %>
        <% elsif examenes_comunidad > 1 %>
          <%= "#{examenes_comunidad} exámenes de la Comunidad Politécnica" %>
        <% end %>
        <% if examenes_publico == 1 %>
          <%= " y 1 examen de Público General" %>
        <% elsif examenes_publico == 0 %>
        <% elsif examenes_publico > 1 %>
          <%= " y #{examenes_publico} exámenes de Público General" %>
        <% end %>
        </li>
      </ul>
      <p>&nbsp;</p>
      <p>Realizando las siguientes actividades:</p>
      <p>&nbsp;</p>
      <ul>
        <li><u>Aplicación de exámenes de colocación.</u></li>
      </ul>
      <p>&nbsp;</p>
      <p>Durante el periodo <%= @periodo %> de <%= @anio %>,
        <% if @curso.include? "Intensivo" %>
          <%= "de lunes a viernes," %>
        <% elsif @curso.include? "Sabatino" %>
          <%= "los sábados," %>
        <% end %>
        con sede en las instalaciones de este CEC Ingeniero Méndez Docurro.</p>
      <p>Además, hacemos de su conocimiento que las actividades realizadas fueron cubiertas en tiempo y forma, existiendo las evidencias
        correspondientes bajo el resguardo en este departamento.</p>
      <p>Se extiende la presente para notificar la autorización del pago correspondiente.</p>
    <table width="690">
      <tr>
        <td width="284" valign="top">

            <p align="center"><strong>&nbsp;</strong></p>
            <p align="center"><strong>&nbsp;</strong></p>

          <p align="center"><strong>ANA LAURA DÍAZ BARROSO</strong><br><strong>COORDINADOR DE LOS CELEX CEC<br>INGENIERO EUGENIO MÉNDEZ DOCURRO.</strong></td>
        <td width="210" valign="top">

            <p align="center"><strong>&nbsp;</strong></p>
            <p align="center"><strong>&nbsp;</strong></p>

          <p align="center"><strong><p align="center">M. EN C. JOSÉ ANTONIO SIXTO BERROCAL<br><strong>SUBDIRECTOR DE SERVICIOS EDUCATIVOS</strong></p></strong></p></td>
      </tr>
    </table>
    <p style="page-break-after: always;">&nbsp;</p>
<% end %>
</div>

app/views/anexos_unicos_examen/index.html.erb
<h2 class="sub">Generar anexos únicos</h2>
<%= form_tag(imprimir_anexo_unico_anexos_unicos_examen_path, method: :get) do %>
<div class="row">
  <div class="col-md-3">
      <%= label_tag 'Elija el curso' %>
      <%= select_tag :curso, options_for_select(CursoNombre.options_for_select), prompt: 'Seleccione', class: 'form-control' %>
      <br>
      <%= label_tag 'Elija el año' %>
      <%= select_tag :anio, options_for_select([["2017","2017"],["2018","2018"]]), prompt: 'Seleccione', class: 'form-control' %>
      <br>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
      <table class="table table-bordered table-hover">
        <thead>
            <th></th>
            <th>Apellido paterno</th>
            <th>Apellido materno</th>
            <th>Nombre</th>
          </tr>
        </thead>

        <tbody>
            <% @users.each do |user| %>
                <tr>
                  <td><%= check_box_tag "user_ids[]", user.id %></td>
                  <td><%= user.paterno %></td>
                  <td><%= user.materno %></td>
                  <td><%= user.nombre %></td>
                </tr>
            <% end %>
        </tbody>
      </table>
      <input type="checkbox" id="selectAll" value="selectAll"><strong> Seleccionar / Deseleccionar todos</strong><br><br>
      <script>
      $('#selectAll').click(function() {
         if (this.checked) {
             $(':checkbox').each(function() {
                 this.checked = true;
             });
         } else {
            $(':checkbox').each(function() {
                 this.checked = false;
             });
         }
      });
      </script>
      <%= submit_tag 'Enviar', name: nil, class:'btn btn-md btn-primary' %>
  </div>
</div>
<% end %>
<br>