config/routes.rb
Rails.application.routes.draw do

  get 'panel_instructor_diplomados', to: 'panel_instructor_diplomados#index'
  get 'calificacion_diplomados', to: 'panel_instructor_diplomados#calificacion_diplomados'

  resources :inscripcion_diplomados
  resources :calificacion_modulos do
    collection do
      patch 'actualizar_calificaciones'
    end
  end
  resources :grupos_diplomados do
    collection do
      get 'acta/:id', to: 'grupos_diplomados#acta', as: 'acta'
      get 'lista_dec/:id', to: 'grupos_diplomados#lista_dec', as: 'lista_dec'
      get 'lista_cec/:id', to: 'grupos_diplomados#lista_cec', as: 'lista_cec'
      get 'expedicion_diplomas/:id', to: 'grupos_diplomados#expedicion_diplomas', as: 'expedicion_diplomas'
    end
  end
  resources :diplomados
  resources :buscar_cartas do
    collection do
      get :carta
    end
  end

  resources :grupos_unitarios do
    collection do
      get 'grupo_excel/:id', to: 'grupos_unitarios#grupo_excel', as: 'grupo_excel'
      get 'grupo_correo/:id', to: 'grupos_unitarios#grupo_correo', as: 'grupo_correo'
    end
  end
  resources :unitarios do
    collection do
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'asignar_grupos_nms_s'
      get 'grupos_nms_s'
      patch 'actualizar_grupos_nms_s'
      get '/credenciales_media/:id', to: 'unitarios#credenciales_media', as: 'credenciales_media'
      get '/carta_compromiso/:id', to: 'unitarios#carta_compromiso', as: 'carta_compromiso'
      get 'reporte_dems'
      get 'reporte_no_validados'
      get 'reporte_contactos'
      get 'generar_credenciales'
      get 'imprimir_credenciales_media'
      get 'imprimir_credenciales_superior'
      get 'imprimir_credenciales_media_grupo'
      get 'imprimir_credenciales_superior_grupo'
    end
  end
  resources :anexos_unicos_examen do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :seccion_nombres
  resources :anexos_unicos do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :it_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'it_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :fr_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'fr_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :curriculums
  resources :registro_cursos
  resources :examen_colocacion_idiomas
  resources :constancia
  resources :historial_carta
  resources :grupo_datos
  resources :datos_bancos
  resources :numero_registros
  resources :proyectos
  resources :clave_catalogos
  resources :cuota_cursos
  resources :modalidad_oferta
  resources :tipo_oferta
  resources :centros
  resources :materia
  resources :lugar_nombres
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :roles
  resources :users do
    collection do
      get 'instructores'
      get 'historiales_ingles'
      get 'historial_ingles/:id', to: 'users#historial_ingles', as: 'historial_ingles'
      get 'anexos_unicos/:id', to: 'users#anexos_unicos', as: 'anexos_unicos'
      get 'conclusion_eventos', to: 'users#conclusion_eventos', as: 'conclusion_eventos'
      get 'datos_anexo_unico'
      get 'generar_anexo_unico'
      get 'historial_academico_ingles/:id', to: 'users#historial_academico_ingles', as: 'historial_academico_ingles'
      get 'historiales_frances'
      get 'historial_frances/:id', to: 'users#historial_frances', as: 'historial_frances'
      get 'historial_academico_frances/:id', to: 'users#historial_academico_frances', as: 'historial_academico_frances'
      get 'historiales_italiano'
      get 'historial_italiano/:id', to: 'users#historial_italiano', as: 'historial_italiano'
      get 'historial_academico_italiano/:id', to: 'users#historial_academico_italiano', as: 'historial_academico_italiano'
      get 'historiales_b2'
      get 'historial_b2/:id', to: 'users#historial_b2', as: 'historial_b2'
      get 'historial_academico_b2/:id', to: 'users#historial_academico_b2', as: 'historial_academico_b2'
      get 'historiales_tkt'
      get 'historial_tkt/:id', to: 'users#historial_tkt', as: 'historial_tkt'
      get 'historial_academico_tkt/:id', to: 'users#historial_academico_tkt', as: 'historial_academico_tkt'
      get 'historiales'
    end
  end
  resources :estados
  resources :grupos do
    collection do
      post 'edit_multiple'
      patch 'update_multiple'
      get 'crear_constancias/:id', to: 'grupos#crear_constancias',  as: 'crear_constancias'
      get 'calificaciones/:id', to: 'grupos#calificaciones', as: 'calificaciones'
      get 'apertura/:id', to: 'grupos#apertura', as: 'apertura'
      get 'lista_asistencia/:id', to: 'grupos#lista_asistencia', as: 'lista_asistencia'
      get 'supervisar/:id', to: 'grupos#supervisar', as: 'supervisar'
    end
  end
  #resources :profesor_nombres
  resources :generos
  resources :curso_nombres
  resources :calendarios
  resources :procedencia
  resources :cuota
  resources :nivel_nombres
  resources :idiomas
  resources :horarios
  resources :inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec_frances'
      get 'reporte_dec_italiano'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'caso_especial'
      post 'guardar_caso_especial'
      get 'certificacion'
      get '/talon/:id', to: 'inscripcion_registros#talon', as: 'talon'
      get '/constancia_avanzado/:id', to: 'inscripcion_registros#constancia_avanzado', as: 'constancia_avanzado'
      get 'ver_constancias_tkt'
      get '/constancia_tkt/:id', to: 'inscripcion_registros#constancia_tkt', as: 'constancia_tkt'
      get 'ver_constancias_b2'
      get '/constancia_b2/:id', to: 'inscripcion_registros#constancia_b2', as: 'constancia_b2'
    end
  end
  resources :panel_alumnos do
    collection do
      get 'facturacion'
      get 'regulaciones'
    end
  end
  resources :panel_profesores do
    collection do
      get 'mis_grupos'
      get 'historial_academico'
    end
  end
  get '/panel_control_escolar/', to: 'panel_control_escolar#index'

  resources :reinscripcion_registros do
    collection do
      get :boleta
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_scope :user do
    #root to: "devise/sessions#new"
  #end
  root to: "inicio#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :nombre, :paterno, :rfc, presence: true

  # Opciones de devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Filtros de filterrific
         filterrific(
           available_filters: [
             :search_query,
             :with_role_id,
           ]
         )

  # Asociaciones con otros modelos
  belongs_to :role

  belongs_to :centro

  has_many :inscripcion_registros, dependent: :destroy

  has_many :fr_inscripcion_registros, dependent: :destroy

  has_many :it_inscripcion_registros, dependent: :destroy

  before_save :assign_role

  before_save :assign_centro

  has_many :grupos

  has_many :calendarios

  has_many :examen_colocacion_idiomas

  has_many :curriculums, dependent: :destroy

  # Opciones de kaminari para la paginación de los registros del modelo (25 en este caso)
  paginates_per 50

  # Definición de roles para devise
  def assign_role
    self.role = Role.find_by nombre: "Invitado" if self.role.nil?
  end

  # Definición de roles para devise
  def assign_centro
    self.centro = Centro.find_by nombre: "Ingeniero Eugenio Méndez Docurro" if self.centro.nil?
  end

  # Definiciones de los roles dentro del sistema
  def invitado?
    self.role.nombre == "Invitado"
  end

  def profesor?
    self.role.nombre == "Profesor"
  end

  def control_cec?
    self.role.nombre == "Control escolar"
  end

  def coordinador_celex?
    self.role.nombre = "Coordinación CELEX"
  end

  def admin?
    self.role.nombre == "Administrador"
  end

  def jefe_ec?
    self.role.nombre == "Jefe Educación Continua"
  end

  def jefe_cec?
    self.role.nombre == "Director del Centro"
  end

  def control_ec?
    self.role.nombre == "Cursos control"
  end

  def control_dp_ec?
    self.role.nombre == "Diplomados control"
  end

  def instructor_dp?
    self.role.nombre == "Instructor diplomados"
  end

  # Se utiliza para mostrar el nombre completo de un usuario, principalmente de
  # los alumnos, de esta forma en las listas de registros de inscripción aparecen
  # primero por apellidos para que puedan buscarse de forma más sencilla
  def nombre_completo
    "#{paterno} #{materno} #{nombre}"
  end

  # Se usa para darle el formato "Nombre(s) Apellido Paterno Apellido Materno" a
  # los usuarios en los historiales académicos y en las constancias de idioma.
  def nombre_paterno_materno
    "#{nombre} #{paterno} #{materno}"
  end

  def nombre_upcase
    self.nombre_completo.parameterize(separator: ' ').upcase
  end

  def escolaridad_nombre_paterno_materno
    "#{escolaridad} #{nombre} #{paterno} #{materno}"
  end

  # Se utiliza para obtener al Director del centro, éste aparece
  # principalmente en los formatos de apertura de grupos del Sistema de
  # Gestión de Calidad, en los historiales acedémicos y en las listas del grupos
  # que tienen el formato del Sistema de Gestión de Calidad.
  def self.director
    rol = Role.find_by(nombre: "Director").id
    usuarios = User.find_by(role: rol).escolaridad_nombre_paterno_materno
  end

  # Se utiliza para obtener al Director del centro, éste aparece
  # principalmente en los formatos de apertura de grupos del Sistema de
  # Gestión de Calidad, en los historiales acedémicos y en las listas del grupos
  # que tienen el formato del Sistema de Gestión de Calidad.
  def self.subdirector
    rol = Role.find_by(nombre: "Subdirector").id
    usuarios = User.find_by(role: rol).escolaridad_nombre_paterno_materno
  end

  # Se utiliza para obtener al Jefe de Educación Continua actual, éste aparece
  # principalmente en los formatos de apertura de grupos del Sistema de
  # Gestión de Calidad, en los historiales acedémicos y en las listas del grupos
  # que tienen el formato del Sistema de Gestión de Calidad.
  def self.jefe_educacion_continua
    rol = Role.find_by(nombre: "Jefe Educación Continua").id
    usuarios = User.find_by(role: rol).escolaridad_nombre_paterno_materno
  end

  # Se utiliza para filtrar a los alumnos en las listas para calificaciones,
  # las listas del Sistema de Gestión de Calidad, para las constancias y
  # para la lista de usuarios en el sistema.
  def self.alumnos
    rol = Role.find_by(nombre: "Invitado").id
    usuarios = User.where(role: rol)
  end

  # Se utiliza para la lista de instructores en la lista de usuarios del sistema
  # además, se utiliza para la lista de CV de instructores.
  def self.instructores
    rol = Role.find_by(nombre: "Profesor").id
    usuarios = User.where(role: rol)
  end

  # Se utiliza para filtrar la lista de usuarios por instructores de diplomados
  # en la vista de creacion de diplomados
  def self.instructores_diplomados
    rol = Role.find_by(nombre: "Instructor diplomados").id
    usuarios = User.where(role: rol)
  end

  def self.nombre_instructores
    rol = Role.find_by(nombre: "Profesor").id
    usuarios = User.where(role: rol)
    usuarios.map { |e| [e.nombre_completo, e.id] }
  end

  # Función que calcula la edad de una persona (usuario) a partir de su CURP
  def edad
    curp = "#{rfc}"
    curp = curp.scan(/\d{6}/)
    curp = curp.join
    curp = Time.parse(curp)
    hoy = Date.today
    edad = hoy.year - curp.year
  end

  # Función que determina el sexo de una persona (usuario) a partir de su CURP
  def sexo
    sexo = "#{rfc}"
    sexo = sexo.scan(/^.{10}[HM]/)
    sexo = sexo.join
    sexo = sexo[-1...11]
  end

  # Definición de los filtros para filterrific
  scope :search_query, lambda { |query|

    # Filtra a los usuarios por nombre o apellido paterno
    return nil  if query.blank?

    # Condiciones del query divididas en palabras separadas y en minúsculas
    terms = query.downcase.split(/\s+/)

    # Reemplaza "*" con "%" para búsquedas con comodin,
    # liga '%', quita los '%' duplicados
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }

    # Configura el numero de condiciones OR proporcionados (provision)
    # como argumentos de interpolación. Ajustar si se cambian el
    # número de condiciones OR.
    num_or_conds = 3

    where(
      terms.map { |term|
        "(LOWER(users.nombre) LIKE ? OR LOWER(users.paterno) LIKE ? OR LOWER(users.materno) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }
  scope :with_role_id, lambda { |role_ids|
    # Se filtra a los usuarios dependiendo del role_id dado
    where(role_id: [*role_ids])
  }

end

app/helpers/fr_inscripcion_registros_helper.rb
module FrInscripcionRegistrosHelper
end

app/views/fr_inscripcion_registros/_links.html.erb
<% if user_signed_in? && current_user.role.nombre == 'Invitado' %>
  <%= link_to 'Regresar', panel_alumnos_path %>
<% elsif user_signed_in? && current_user.role.nombre == 'Administrador' %>
  <%= link_to 'Regresar', fr_inscripcion_registros_path %>
<% elsif user_signed_in? && current_user.role.nombre == 'Control escolar' %>
  <%= link_to 'Regresar', fr_inscripcion_registros_path %>
<% elsif user_signed_in? && current_user.role.nombre == 'Profesor' %>
  <%= link_to 'Regresar', :back %>
<% end %>

app/views/fr_inscripcion_registros/_lista_reporte.html.erb
<div id="filterrific_results">
  <table class="table table-bordered table-condensed table-small-font">
    <thead>
      <tr>
        <th>N&uacute;m prog.</th>
        <th>A. Paterno</th>
        <th>A. Materno</th>
        <th>Nombre(s)</th>
        <th>Nivel</th>
        <th>Horario</th>
        <th>Idioma</th>
        <th>Cantidad depositada</th>
        <th>Movimiento bancario</th>
        <th>Comunidad</th>
        <th>Curso</th>
        <th>A&ntilde;o</th>
      </tr>
    </thead>

    <tbody>
      <% @fr_inscripcion_registros.each_with_index do |fr_inscripcion_registro, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= fr_inscripcion_registro.paterno_upcase %></td>
          <td><%= fr_inscripcion_registro.materno_upcase %></td>
          <td><%= fr_inscripcion_registro.nombre_upcase %></td>
          <td><%= fr_inscripcion_registro.nivel.mb_chars.upcase %></td>
          <td><%= fr_inscripcion_registro.horario %></td>
          <td><%= fr_inscripcion_registro.idioma.mb_chars.upcase %></td>
          <td>$<%= fr_inscripcion_registro.monto_pagado %></td>
          <td><%= fr_inscripcion_registro.movimiento %></td>
          <td><%= fr_inscripcion_registro.procedencia.mb_chars.upcase %></td>
          <td><%= fr_inscripcion_registro.curso.upcase %></td>
          <td><%= fr_inscripcion_registro.created_at.strftime("%Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @fr_inscripcion_registros, theme: 'twitter-bootstrap-3', param_name: :pagina %>
</div>

app/views/fr_inscripcion_registros/_registros.html.erb
<%= form_tag editar_datos_fr_inscripcion_registros_path, method: :get do %>
<div id="filterrific_results">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Seleccionar</td>
        <th>Nombre</th>
        <th>Monto de la cuota</th>
        <th>Monto pagado</th>
        <th>Movimiento bancario</th>
        <th>Comprobante</th>
        <th>Documentos validados</th>
        <th>Fecha de creaci&oacute;n</th>
        <th>Fecha de actualizaci&oacute;n</th>
        <th>Grupo</th>
        <th colspan="3">Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @fr_inscripcion_registros.each do |fr_inscripcion_registro| %>
        <tr>
          <td><%= check_box_tag "fr_inscripcion_registro_ids[]", fr_inscripcion_registro.id %></td>
          <td><%= fr_inscripcion_registro.nombre_upcase %> <%= fr_inscripcion_registro.paterno_upcase %> <%= fr_inscripcion_registro.materno_upcase %></td>
          <td>$<%= fr_inscripcion_registro.cuota %></td>
          <td>$<%= fr_inscripcion_registro.monto_pagado %></td>
          <td><%= fr_inscripcion_registro.movimiento %></td>
          <% if fr_inscripcion_registro.imagen.exists? %>
            <td>
              <%= link_to fr_inscripcion_registro.imagen.url(:medium), target: '_blank', class:'btn btn-comprobante' do %>
                <span class="glyphicon glyphicon-paperclip"></span> Comprobante
              <% end %>
            </td>
          <% else %>
            <td>
              <strong>Sin comprobante</strong>
            </td>
          <% end %>
          <% if fr_inscripcion_registro.documentos_validados == true %>
            <td class="success"><%= fr_inscripcion_registro.documentos_validados ? 'Si' : 'No' %></td>
          <% else %>
            <td class="danger"><%= fr_inscripcion_registro.documentos_validados ? 'Si' : 'No' %></td>
          <% end %>
          <td><%= fr_inscripcion_registro.created_at.strftime("%d/%m/%y a las %T %P") %></td>
          <td><%= fr_inscripcion_registro.updated_at.strftime("%d/%m/%y a las %T %P") %></td>
          <td class="info"><%= fr_inscripcion_registro.grupo.nombre %></td>
          <td><%= link_to 'Talón', fr_inscripcion_registro %></td>
          <td><%= link_to 'Editar', edit_fr_inscripcion_registro_path(fr_inscripcion_registro) %></td>
          <td><%= link_to 'Eliminar', fr_inscripcion_registro, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @fr_inscripcion_registros, theme: 'twitter-bootstrap-3', param_name: :pagina %>
  <br><br>
  <input type="checkbox" id="selectAll" value="selectAll"><strong> Seleccionar / Deseleccionar todos</strong><br><br>
  <%= submit_tag "Editar seleccionados", class: 'btn btn-primary' %>
</div>
<% end %>
<script>
$('#selectAll').click(function() {
   if (this.checked) {
       $(':checkbox').each(function() {
           this.checked = true;
       });
   } else {
      $(':checkbox').each(function() {
           this.checked = false;
       });
   }
});
</script>

app/views/fr_inscripcion_registros/constancia.html.erb
<div id="constancia">
  <table class="constancia">
      <tr>
        <td width="50%"><%= image_tag "sep.jpg" %></td>
        <td></td>
        <td></td>
        <td width="50%"><%= image_tag "logoipn.jpg", style: 'float: right; margin: 0px 0px 15px 0px;' %><p class="texto-ipn">Instituto Polit&eacute;cnico Nacional<br>&ldquo;La t&eacute;cnica al servicio de la Patria&rdquo;</p></td>
      </tr>
      <tr>
        <td colspan="4"><p align="center" class="dependencia">Secretaría de Extensión e Integración Social<br>Dirección de educación continua</p></td>
      </tr>
      <tr>
        <td colspan="4"><p align="center" class="otorga">Otorga la presente</p><p class="constancia" align="center">CONSTANCIA</p></td>
      </tr>
      <tr>
        <td colspan="4"><p align="center" class="nombre_mayusculas">a: <%= @fr_inscripcion_registro.nombre_completo %></p></td>
      </tr>
      <tr>
        <td colspan="4"><p align="center">Por haber participado en el curso: <strong>"<%= @fr_inscripcion_registro.grupo.nombre_grupo     %>"</strong>, del <%= @fr_inscripcion_registro.grupo.periodo %> de 2017, impartido en el Centro de Educación Continua Eugenio Mendez Docurro, con una duración de 40 horas.</p></td>
      </tr>
      <tr>
        <td colspan="4"><p align="center">____________________________________<br><strong>Ing. José Manuel Guillermo García Macías</strong><br>Director de Educación Continua<br></p></td>
      </tr>
  </table>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p align="center" class="dependencia"><strong>INSTITUTO POLIT&Eacute;NICO NACIONAL</strong></p>
  <p align="center" class="dependencia"><strong>SECRETAR&Iacute;A DE EXTENSI&Oacute;N E INTEGRACI&Oacute;N SOCIAL</strong></p>
  <p align="center" class="dependencia"><strong>DIRECCI&Oacute;N DE EDUCACI&Oacute;N CONTINUA</strong></p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p align="center" class="dependencia">CURSO</p>
  <p align="center" class="dependencia"><%= @fr_inscripcion_registro.grupo.registro %></p>
  <p>&nbsp;</p>
  <p align="center" class="dependencia"><strong><%= @fr_inscripcion_registro.grupo.nombre_grupo %></strong></p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <table class="table table-bordered">
    <tr>
      <td><p align="center">PROGRAMA TEM&Aacute;TICO</p></td>
      <td><p align="center">DURACI&Oacute;N</p></td>
      <td><p align="center">PERIODO</p></td>
    </tr>
    <tr>
      <td><p>1. Competencia A<br>2.Competencia B<br>3. Competencia C</p></td>
      <td><p align="center"><%= @fr_inscripcion_registro.grupo.duracion %></p></td>
      <td><p align="center"><%= @fr_inscripcion_registro.grupo.periodo %></p></td>
    </tr>
  </table>
  <table width="100%">
    <tr>
      <td width="50%"><p>Nombre del participante: <%= @fr_inscripcion_registro.nombre_completo %> <br> Calificaci&oacute;n: <%= @fr_inscripcion_registro.promedio %></p></td>
      <td width="50%"><p>El instituto Polit&eacute;cnico Nacional, a trav&eacute;s de la Direcci&oacute;n de Educaci&oacute;n Continua hace constrar que este Documento ha quedado registrado en sus archivos en el libro a&ntilde;o:</p></td>
    </tr>
  </table>
  <p>&nbsp;</p>
  <table width="100%">
  <tr>
    <td colspan="2"><p align="center">AVALA EL REGISTRO</p><br><br></td>
  </tr>
  <tr>
    <td width="50%"><p align="center">____________________________________<br><strong><%= @fr_inscripcion_registro.grupo.director_centro %></strong><br>Director del Centro de Educación Continua<br>Ingeniero Eugenio M&eacute;ndez Docurro</p></td>
    <td width="50%"><p align="center">____________________________________<br><strong>Biol. Pilar Pi&ntilde;a Espallargas</strong><br>Directora de Formaci&oacute;n en Lenguas Extranjeras<br></p></td>
  </tr>
  <tr>
    <td width="100" colspan="2"><p align="right"><%= image_tag @qr %></p></td>
  </tr>
</table>

</div>
<div class="row">
    <div class="col-md-12">
      <input type="button" id="btn-constancia" value="Imprimir constancia" class="btn btn-md btn-primary">
    </div>
    <div class="col-md-12">
      <%= link_to 'Regresar', ver_constancias_fr_inscripcion_registros_path %>
    </div>
</div>

<script>
$("#btn-constancia").click(function () {
    //Hide all other elements other than printarea.
    $("#constancia").show();
    window.print();
});
</script>

app/views/fr_inscripcion_registros/habilitar_multiples_constancias.html.erb
<h2 class="sub">Las siguientes contancias se van a crear:</h2>
<%= form_for :fr_inscripcion_registro, url: actualizar_multiples_constancias_fr_inscripcion_registros_path, :html => { :method => :patch } do |form| %>
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered">
      <th>Nombre del grupo</td>
      <th>Grupo</th>
      <th>Curso</th>
      <th>A&ntilde;o</th>
      <% @fr_inscripcion_registros.each do |fr_inscripcion_registro| %>
      <tr>
        <td><%= fr_inscripcion_registro.nombre_completo %></td>
        <td><%= fr_inscripcion_registro.grupo.nombre %></td>
        <td><%= fr_inscripcion_registro.curso %></td>
        <td><%= fr_inscripcion_registro.grupo.anio %></td>
        <%= hidden_field_tag "fr_inscripcion_registro_ids[]", fr_inscripcion_registro.id %>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="row">
  <div class="form-group col-sm-4">
    <%= form.label :habilitar_constancia, 'Crear constancia(s)' %>
    <%= form.check_box  :habilitar_constancia, class: 'form-control' %>
  <br>
  </div>
</div>
<div class="row">
  <div class="actions col-sm-4">
    <%= form.submit "Guardar", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

<%= link_to 'Regresar', grupos_path %>

app/views/fr_inscripcion_registros/index.js.erb
<% js = escape_javascript(
  render(partial: 'fr_inscripcion_registros/registros', locals: { fr_inscripcion_registros: @fr_inscripcion_registros })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/fr_inscripcion_registros/reporte_curso.js.erb
<% js = escape_javascript(
  render(partial: 'fr_inscripcion_registros/lista_reporte', locals: { fr_inscripcion_registros: @fr_inscripcion_registros })
) %>
$("#filterrific_results").html("<%= js %>");