config/routes.rb
Rails.application.routes.draw do

  get 'panel_instructor_diplomados', to: 'panel_instructor_diplomados#index'
  get 'calificacion_diplomados', to: 'panel_instructor_diplomados#calificacion_diplomados'

  resources :inscripcion_diplomados
  resources :calificacion_modulos do
    collection do
      patch 'actualizar_calificaciones'
    end
  end
  resources :grupos_diplomados do
    collection do
      get 'acta/:id', to: 'grupos_diplomados#acta', as: 'acta'
      get 'lista_dec/:id', to: 'grupos_diplomados#lista_dec', as: 'lista_dec'
      get 'lista_cec/:id', to: 'grupos_diplomados#lista_cec', as: 'lista_cec'
      get 'expedicion_diplomas/:id', to: 'grupos_diplomados#expedicion_diplomas', as: 'expedicion_diplomas'
    end
  end
  resources :diplomados
  resources :buscar_cartas do
    collection do
      get :carta
    end
  end

  resources :grupos_unitarios do
    collection do
      get 'grupo_excel/:id', to: 'grupos_unitarios#grupo_excel', as: 'grupo_excel'
      get 'grupo_correo/:id', to: 'grupos_unitarios#grupo_correo', as: 'grupo_correo'
    end
  end
  resources :unitarios do
    collection do
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'asignar_grupos_nms_s'
      get 'grupos_nms_s'
      patch 'actualizar_grupos_nms_s'
      get '/credenciales_media/:id', to: 'unitarios#credenciales_media', as: 'credenciales_media'
      get '/carta_compromiso/:id', to: 'unitarios#carta_compromiso', as: 'carta_compromiso'
      get 'reporte_dems'
      get 'reporte_no_validados'
      get 'reporte_contactos'
      get 'generar_credenciales'
      get 'imprimir_credenciales_media'
      get 'imprimir_credenciales_superior'
      get 'imprimir_credenciales_media_grupo'
      get 'imprimir_credenciales_superior_grupo'
    end
  end
  resources :anexos_unicos_examen do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :seccion_nombres
  resources :anexos_unicos do
    collection do
      get 'index'
      get 'imprimir_anexo_unico'
    end
  end
  resources :it_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'it_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :fr_inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      post 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get '/talon/:id', to: 'fr_inscripcion_registros#talon', as: 'talon'
      get 'caso_especial'
      post 'guardar_caso_especial'
    end
  end
  resources :curriculums
  resources :registro_cursos
  resources :examen_colocacion_idiomas
  resources :constancia
  resources :historial_carta
  resources :grupo_datos
  resources :datos_bancos
  resources :numero_registros
  resources :proyectos
  resources :clave_catalogos
  resources :cuota_cursos
  resources :modalidad_oferta
  resources :tipo_oferta
  resources :centros
  resources :materia
  resources :lugar_nombres
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :roles
  resources :users do
    collection do
      get 'instructores'
      get 'historiales_ingles'
      get 'historial_ingles/:id', to: 'users#historial_ingles', as: 'historial_ingles'
      get 'anexos_unicos/:id', to: 'users#anexos_unicos', as: 'anexos_unicos'
      get 'conclusion_eventos', to: 'users#conclusion_eventos', as: 'conclusion_eventos'
      get 'datos_anexo_unico'
      get 'generar_anexo_unico'
      get 'historial_academico_ingles/:id', to: 'users#historial_academico_ingles', as: 'historial_academico_ingles'
      get 'historiales_frances'
      get 'historial_frances/:id', to: 'users#historial_frances', as: 'historial_frances'
      get 'historial_academico_frances/:id', to: 'users#historial_academico_frances', as: 'historial_academico_frances'
      get 'historiales_italiano'
      get 'historial_italiano/:id', to: 'users#historial_italiano', as: 'historial_italiano'
      get 'historial_academico_italiano/:id', to: 'users#historial_academico_italiano', as: 'historial_academico_italiano'
      get 'historiales_b2'
      get 'historial_b2/:id', to: 'users#historial_b2', as: 'historial_b2'
      get 'historial_academico_b2/:id', to: 'users#historial_academico_b2', as: 'historial_academico_b2'
      get 'historiales_tkt'
      get 'historial_tkt/:id', to: 'users#historial_tkt', as: 'historial_tkt'
      get 'historial_academico_tkt/:id', to: 'users#historial_academico_tkt', as: 'historial_academico_tkt'
      get 'historiales'
    end
  end
  resources :estados
  resources :grupos do
    collection do
      post 'edit_multiple'
      patch 'update_multiple'
      get 'crear_constancias/:id', to: 'grupos#crear_constancias',  as: 'crear_constancias'
      get 'calificaciones/:id', to: 'grupos#calificaciones', as: 'calificaciones'
      get 'apertura/:id', to: 'grupos#apertura', as: 'apertura'
      get 'lista_asistencia/:id', to: 'grupos#lista_asistencia', as: 'lista_asistencia'
      get 'supervisar/:id', to: 'grupos#supervisar', as: 'supervisar'
    end
  end
  #resources :profesor_nombres
  resources :generos
  resources :curso_nombres
  resources :calendarios
  resources :procedencia
  resources :cuota
  resources :nivel_nombres
  resources :idiomas
  resources :horarios
  resources :inscripcion_registros do
    collection do
      post 'habilitar_multiples_constancias'
      patch 'actualizar_multiples_constancias'
      get 'ver_constancias'
      get 'constancia/:id', to: 'inscripcion_registros#constancia',  as: 'constancia'
      post 'imprimir'
      get 'asignar_calificaciones'
      patch 'actualizar_asignar_calificaciones'
      get 'reporte_curso'
      get 'reporte_dec_frances'
      get 'reporte_dec_italiano'
      get 'reporte_dec'
      get 'editar_datos'
      patch 'actualizar_editar_datos'
      get 'caso_especial'
      post 'guardar_caso_especial'
      get 'certificacion'
      get '/talon/:id', to: 'inscripcion_registros#talon', as: 'talon'
      get '/constancia_avanzado/:id', to: 'inscripcion_registros#constancia_avanzado', as: 'constancia_avanzado'
      get 'ver_constancias_tkt'
      get '/constancia_tkt/:id', to: 'inscripcion_registros#constancia_tkt', as: 'constancia_tkt'
      get 'ver_constancias_b2'
      get '/constancia_b2/:id', to: 'inscripcion_registros#constancia_b2', as: 'constancia_b2'
    end
  end
  resources :panel_alumnos do
    collection do
      get 'facturacion'
      get 'regulaciones'
    end
  end
  resources :panel_profesores do
    collection do
      get 'mis_grupos'
      get 'historial_academico'
    end
  end
  get '/panel_control_escolar/', to: 'panel_control_escolar#index'

  resources :reinscripcion_registros do
    collection do
      get :boleta
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_scope :user do
    #root to: "devise/sessions#new"
  #end
  root to: "inicio#index"
end

app/models/inscripcion_diplomado.rb
class InscripcionDiplomado < ApplicationRecord
  belongs_to :grupos_diplomado
  has_many :calificacion_modulos, dependent: :destroy
  accepts_nested_attributes_for :calificacion_modulos, allow_destroy: true

  #Filtros de filterrific disponibles para el controlador
  filterrific(
    available_filters: [
      :search_query,
      :with_grupos_unitario_id,
      :with_documentos_validados,
    ]
  )

  # Número de páginas por vista
  paginates_per 25


  #Filtro para buscar por nombre o apellido
  scope :search_query, lambda { |query|

    # No devuelve resultados si el campo de texto está en blanco
    return nil  if query.blank?

    # Condiciones del query divididas en palabras separadas y en minúsculas
    terms = query.downcase.split(/\s+/)

    # Reemplaza "*" con "%" para búsquedas con comodin,
    # liga '%', quita los '%' duplicados
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }

    # Configura el numero de condiciones OR proporcionados (provision)
    # como argumentos de interpolación. Ajustar si se cambian el
    # número de condiciones OR.
    num_or_conds = 3

    where(
      terms.map { |term|
        "(LOWER(inscripcion_diplomados.nombre) LIKE ? OR LOWER(inscripcion_diplomados.paterno) LIKE ?
        OR LOWER(inscripcion_diplomados.materno) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  # Filtro para agrupas los registros de inscripción por grupos
  scope :with_grupos_diplomado_id, lambda { |grupos_diplomado_ids|
    # Se filtra a los usuarios dependiendo del grupos_diplomado_id dado
    where(grupos_diplomado_id: [*grupos_diplomado_ids])
  }

  # Filtro para agrupar los registros de inscripción por la validación de documentos
  scope :with_documentos_validados, lambda { |documentos_validados|
    where(documentos_validados: [*documentos_validados])
  }

  # Opciones para la lista de selección del filtro ":with_documentos_validados"
  def self.options_for_documentos_validados
    [
      ['Validado','1'],
      ['No validado', '0']
    ]
  end

end

app/controllers/inscripcion_diplomados_controller.rb
class InscripcionDiplomadosController < ApplicationController
  before_action :authenticate_user!, except: [:create, :new]
  before_action :set_inscripcion_diplomado, only: [:show, :edit, :update, :destroy]


  # GET /inscripcion_diplomados
  # GET /inscripcion_diplomados.json
  def index
    #@unitarios = Unitario.all
    #@grupos_unitarios = GruposUnitario.all
    @filterrific = initialize_filterrific(
    InscripcionDiplomado,
    params[:filterrific],
    select_options: {
      with_grupos_unitario_id: GruposDiplomado.seleccion_curso_nombre,
      with_documentos_validados: InscripcionDiplomado.options_for_documentos_validados
    },
  ) or return
  @inscripcion_diplomados = @filterrific.find.page(params[:pagina])

  respond_to do |format|
    format.html
    format.js
  end

  rescue ActiveRecord::RecordNotFound => e
  # There is an issue with the persisted param_set. Reset it.
  puts "Se restablecieron los parámetros: #{ e.message }"
  redirect_to(reset_filterrific_url(format: :html)) and return
  end

  # GET /inscripcion_diplomados/1
  # GET /inscripcion_diplomados/1.json
  def show
    @calificacion_modulos = CalificacionModulo.where(inscripcion_diplomado_id: @inscripcion_diplomado.id)
  end

  # GET /inscripcion_diplomados/new
  def new
    @inscripcion_diplomado = InscripcionDiplomado.new
    @calificacion_modulos = []
    #15.times do
      #@calificacion_modulos << CalificacionModulo.new
    #end
  end

  # GET /inscripcion_diplomados/1/edit
  def edit
    @calificacion_modulos = CalificacionModulo.where(inscripcion_diplomado_id: @inscripcion_diplomado.id)
  end

  # POST /inscripcion_diplomados
  # POST /inscripcion_diplomados.json
  def create

    @inscripcion_diplomado = InscripcionDiplomado.new(inscripcion_diplomado_params)
    grupo_id = GruposDiplomado.find_by(diplomado_id: @inscripcion_diplomado.diplomado_id).id
    @inscripcion_diplomado.grupos_diplomado_id = grupo_id
    # Se calcula el número de módulos que tiene el diplomado al que se inscribe
    # el usuario para crear ese mismo número de campos de calificación.
    #modulos = inscripcion_diplomado.grupos_diplomado.numero_modulos
    modulos = ModuloDiplomado.where(diplomado_id: @inscripcion_diplomado.diplomado_id)

    respond_to do |format|
      if @inscripcion_diplomado.save
        # Se guardan al mismo tiempo los datos de la inscripción y el número de
        # espacios de calificación para ese usuario.
        modulos.each do |modulo|
          CalificacionModulo.create(calificacion: "", inscripcion_diplomado_id: @inscripcion_diplomado.id,
          instructor_id: modulo.instructor_id, numero_modulo: modulo.numero_modulo, asistencia: "")
        end
        format.html { redirect_to new_inscripcion_diplomado_path, notice: 'La inscripción al diplomado fue creada correctamente.' }
        format.json { render :show, status: :created, location: @inscripcion_diplomado }
      else
        format.html { render :new }
        format.json { render json: @inscripcion_diplomado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inscripcion_diplomados/1
  # PATCH/PUT /inscripcion_diplomados/1.json
  def update
    respond_to do |format|
      if @inscripcion_diplomado.update(inscripcion_diplomado_params)
        # Se guardan las calificaciones para cada uno de los módulos del
        # diplomado
        CalificacionModulo.update(params[:calificaciones].keys, params[:calificaciones].values)
        format.html { redirect_to @inscripcion_diplomado, notice: 'La inscripción al diplomado fue actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @inscripcion_diplomado }
      else
        format.html { render :edit }
        format.json { render json: @inscripcion_diplomado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inscripcion_diplomados/1
  # DELETE /inscripcion_diplomados/1.json
  def destroy
    @inscripcion_diplomado.destroy
    respond_to do |format|
      format.html { redirect_to inscripcion_diplomados_url, notice: 'La inscripción al diplomado fue eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inscripcion_diplomado
      @inscripcion_diplomado = InscripcionDiplomado.find(params[:id])
    end

    def inscripcion_diplomado
      @inscripcion_diplomado = InscripcionDiplomado.new(inscripcion_diplomado_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inscripcion_diplomado_params
      params.require(:inscripcion_diplomado).permit(:diplomado_id, :curp, :nombre, :paterno, :materno,
      :sexo, :nacimiento, :domicilio, :codigo_postal, :entidad, :delegacion_municipio,
      :telefono_celular, :telefono_fijo, :correo, :procedencia, :grupos_diplomado_id, :tipo_participante,
      :adscripcion, :calificacion_final, :folio, :foja, :proyecto_terminal, :numero_empleado,
      :documentos_validados, calificacion_modulos_attributes: CalificacionModulo.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/helpers/inscripcion_diplomados_helper.rb
module InscripcionDiplomadosHelper
end

app/views/inscripcion_diplomados/_form.html.erb
<%= form_for(inscripcion_diplomado) do |f| %>
  <% if inscripcion_diplomado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inscripcion_diplomado.errors.count, "error") %> prohibited this inscripcion_diplomado from being saved:</h2>

      <ul>
      <% inscripcion_diplomado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row jumbotron">
    <h4 class="subs"><strong>Oferta actual</strong></h4>
    <div class="row">
      <div class="form-group col-sm-7">
        <%= f.label :diplomado_id, 'Nombre del diplomado' %>
        <%= collection_select(:inscripcion_diplomado, :diplomado_id, GruposDiplomado.where(estado: 'Abierto'), :diplomado_id, :nombre_diplomado, {prompt: 'Seleccione'}, class: 'form-control', required: true) %>
      </div>
    </div>
  </div>

  <div class="row jumbotron">
  <h4 class="subs"><strong>Información personal</strong></h4>
  <div class="row">
    <div class="form-group col-sm-3">
      <%= f.label :curp, 'CURP' %><strong><%= link_to '  ¿No conoce su CURP?', 'http://consultas.curp.gob.mx', html_options = {target: '_blank'} %></strong>
      <%= f.text_field :curp, class: 'form-control', required: true, maxlength: 18 %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :nombre, 'Nombre (s)' %>
      <%= f.text_field :nombre, class: 'form-control', required: true %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :paterno, 'Apellido paterno' %>
      <%= f.text_field :paterno, class: 'form-control', required: true %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :materno, 'Apellido materno' %>
      <%= f.text_field :materno, class:'form-control', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-2">
      <%= f.label :sexo %>
      <%= collection_select(:inscripcion_diplomado, :sexo, Genero.all, :genero, :genero, {prompt: 'Seleccione'}, class: 'form-control', required: true) %>
    </div>

    <div class="form-group col-sm-2">
      <%= f.label :nacimiento, 'Fecha de nacimiento' %><br>
      <div class="input-group date">
        <%= f.text_field :nacimiento, class:'nacimiento form-control' %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :domicilio, 'Domicilio (calle, número y colonia)' %>
      <%= f.text_field :domicilio, class:'form-control', required: true %>
    </div>

    <div class="form-group col-sm-2">
      <%= f.label :codigo_postal, 'Código postal'  %>
      <%= f.text_field :codigo_postal, class:'form-control', required: true, maxlength: 5, pattern: '[0-9]+' %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :entidad, 'Entidad federativa' %>
      <%= f.text_field :entidad, class:'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-3">
      <%= f.label :delegacion_municipio, 'Delegación o municipio' %>
      <%= f.text_field :delegacion_municipio, class:'form-control' %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :telefono_celular, 'Teléfono celular' %>
      <%= f.text_field :telefono_celular, class:'form-control', required: true, maxlength: 10, pattern: '[0-9]+' %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :correo, 'Correo electrónico' %>
      <%= f.email_field :correo, class:'form-control', required: true %>
    </div>
    <% if user_signed_in? %>
      <% if can? :validar_documentos, unitario %>
    <div class="form-group col-sm-3">
      <%= f.label :tipo_participante, 'Tipo de participante' %>
      <%= f.text_field :tipo_participante, class:'form-control', required: true %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-3">
      <%= f.label :adscripcion, 'Adscripción' %>
      <%= f.text_field :adscripcion, class:'form-control' %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :calificacion_final, 'Trabajo final' %>
      <%= f.text_field :calificacion_final, class:'form-control' %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :folio, 'Folio' %>
      <%= f.text_field :folio, class:'form-control' %>
    </div>

    <div class="form-group col-sm-3">
      <%= f.label :foja, 'Foja' %>
      <%= f.text_field :foja, class:'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-3">
      <%= f.label :numero_empleado, 'Número de empleado' %>
      <%= f.text_field :numero_empleado, class:'form-control' %>
    </div>

    <div class="form-group col-sm-6">
      <%= f.label :proyecto_terminal, 'Proyecto terminal' %>
      <%= f.text_field :proyecto_terminal, class:'form-control' %>
    </div>
  </div>
    <% end %>
  <% end %>
</div>
<% if user_signed_in? %>
  <% if can? :validar_documentos, unitario %>
<div class="row jumbotron">
  <h4 class="subs"><strong>Control Escolar</strong></h4>
  <div class="row">
    <div class="form-group col-sm-3">
      <%= f.label :documentos_validados %>
      <%= f.check_box :documentos_validados, class:'form-control' %>
    </div>
  </div>
  <div class="row">
    <% @calificacion_modulos.each_with_index do |calificacion_modulo, index| %>
      <%= fields_for 'calificaciones[]', calificacion_modulo do |f| %>
        <div class="row">
          <div class="form-group col-sm-3">
            <%= f.label :calificacion, "Calificación del módulo #{index + 1}" %>
            <%= f.text_field :calificacion, class:'form-control' %>
          </div>
          <div class="form-group col-sm-3">
            <%= f.label :asistencia, "Asistencia del módulo #{index + 1} en %" %>
            <%= f.text_field :asistencia, class:'form-control' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
  <% end %>
<% end %>

<div class="row">
  <div class="actions col-sm-2">
    <%= f.submit 'Enviar', class:'btn btn-primary' %>
  </div>
</div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.nacimiento').datepicker({language: 'es', format: 'dd-mm-yyyy'});
  });
</script>

app/views/inscripcion_diplomados/_registros.html.erb
<div id="filterrific_results">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Documentos validados</th>
        <th>Fecha de creación</th>
        <th>Diplomado</th>
        <th>Grupo de diplomado</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @inscripcion_diplomados.each do |inscripcion_diplomado| %>
        <tr>
          <td><%= inscripcion_diplomado.paterno_materno_nombre %></td>
          <% if inscripcion_diplomado.documentos_validados == true %>
            <td class="success"><%= inscripcion_diplomado.documentos_validados ? 'Si' : 'No' %></td>
          <% else %>
            <td class="danger"><%= inscripcion_diplomado.documentos_validados ? 'Si' : 'No' %></td>
          <% end %>
          <td><%= inscripcion_diplomado.creado %></td>
          <td><%= inscripcion_diplomado.grupos_diplomado.diplomado.nombre %></td>
          <td><%= inscripcion_diplomado.grupos_diplomado.nombre %></td>
          <td><%= link_to 'Mostrar', inscripcion_diplomado %></td>
          <td><%= link_to 'Editar', edit_inscripcion_diplomado_path(inscripcion_diplomado) %></td>
          <td><%= link_to 'Eliminar', inscripcion_diplomado, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @inscripcion_diplomados, theme: 'twitter-bootstrap-3', param_name: :pagina %>
</div>

app/views/inscripcion_diplomados/edit.html.erb
<h1 class="sub">Editar inscripción a diplomado</h1>

<%= render 'form', inscripcion_diplomado: @inscripcion_diplomado %>

<%= link_to 'Mostrar', @inscripcion_diplomado %> |
<%= link_to 'Regresar', inscripcion_diplomados_path %>

app/views/inscripcion_diplomados/index.html.erb
<h1 class="sub">Inscripción a diplomados</h1>

<%= form_for_filterrific @filterrific do |f| %>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-3">
      <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
      <%= f.label :search_query, 'Búsqueda por nombre' %>
      <%= f.text_field(
        :search_query,
        class: 'filterrific-periodically-observed form-control'
      ) %>
    </div>
    <div class="col-md-3">
      <%= f.label :with_grupos_unitario_id, 'Nombre del curso' %>
      <%= f.select(
        :with_grupos_unitario_id,
        @filterrific.select_options[:with_grupos_unitario_id],
        { include_blank: '- Cualquiera -' }, class:'form-control'
      ) %>
      <br>
    </div>
    <div class="col-md-2">
      <%= f.label :with_documentos_validados, 'Filtrar por estado' %>
      <%= f.select(:with_documentos_validados, @filterrific.select_options[:with_documentos_validados], { include_blank: '- Por defecto -'}, class:'form-control') %>
    </div>
    <br>
  </div>

  <div class="row">
      <div class="col-sm-3">
        <%= link_to(
          'Quitar filtros',
          reset_filterrific_url,
          class: 'btn btn-primary'
        ) %>
      </div>
  </div>
</div>
  <%# add an automated spinner to your form when the list is refreshed %>
<% end %>

<%= render(
  partial: 'inscripcion_diplomados/registros',
  locals: { inscripcion_diplomados: @inscripcion_diplomados }
) %>

<%= link_to 'Crear nueva inscrpción a diplomado', new_inscripcion_diplomado_path %>

app/views/inscripcion_diplomados/index.js.erb
<% js = escape_javascript(
  render(partial: 'inscripcion_diplomados/registros', locals: { inscripcion_diplomados: @inscripcion_diplomados })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/inscripcion_diplomados/new.html.erb
<h1 class="sub">Nueva inscripción a diplomado</h1>

<%= render 'form', inscripcion_diplomado: @inscripcion_diplomado %>

<%= link_to 'Regresar', inscripcion_diplomados_path %>

app/views/inscripcion_diplomados/show.html.erb
<p>
  <strong>Curp:</strong>
  <%= @inscripcion_diplomado.curp %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @inscripcion_diplomado.nombre %>
</p>

<p>
  <strong>Paterno:</strong>
  <%= @inscripcion_diplomado.paterno %>
</p>

<p>
  <strong>Materno:</strong>
  <%= @inscripcion_diplomado.materno %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @inscripcion_diplomado.sexo %>
</p>

<p>
  <strong>Nacimiento:</strong>
  <%= @inscripcion_diplomado.nacimiento %>
</p>

<p>
  <strong>Domicilio:</strong>
  <%= @inscripcion_diplomado.domicilio %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @inscripcion_diplomado.codigo_postal %>
</p>

<p>
  <strong>Entidad:</strong>
  <%= @inscripcion_diplomado.entidad %>
</p>

<p>
  <strong>Delegacion municipio:</strong>
  <%= @inscripcion_diplomado.delegacion_municipio %>
</p>

<p>
  <strong>Telefono celular:</strong>
  <%= @inscripcion_diplomado.telefono_celular %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @inscripcion_diplomado.correo %>
</p>

<p>
  <strong>Grupos diplomado:</strong>
  <%= @inscripcion_diplomado.grupos_diplomado.nombre %>
</p>

<p>
  <strong>Documentos validados:</strong>
  <%= @inscripcion_diplomado.documentos_validados %>
</p>

<%= link_to 'Editar', edit_inscripcion_diplomado_path(@inscripcion_diplomado) %> |
<%= link_to 'Regresar', inscripcion_diplomados_path %>